export const questions = [
	{
		question: 'Name a Pokemon who has no thought behind their eyes.',
		answers: [
			{ title: 'Ditto', points: 42 },
			{ title: 'Wooper/Quagsire', points: 19 },
			{ title: 'Slowpoke/Slowbro', points: 15 },
			{ title: 'Magikarp', points: 10 },
			{ title: 'Fuecoco', points: 6 },
			{ title: 'Espurr', points: 5 },
			{ title: 'Bidoof', points: 4 },
			{ title: 'Feebas', points: 3 },
		],
	},
	{
		question: "Name a Pokemon you'd trust to babysit your children.",
		answers: [
			{ title: 'Chansey/Blissey', points: 55 },
			{ title: 'Kangaskhan', points: 22 },
			{ title: 'Mr. Mime', points: 15 },
			{ title: 'Drifloon', points: 10 },
			{ title: 'Audino', points: 9 },
			{ title: 'Bulbasaur', points: 5 },
			{ title: 'Gardevoir', points: 4 },
			{ title: 'Drampa', points: 4 },
		],
	},
	{
		question: 'Name something that shakes, rattles, and rolls.',
		answers: [
			{ title: 'An Old Car', points: 31 },
			{ title: 'A Rattle/Toy', points: 29 },
			{ title: 'A Rattlesnake', points: 15 },
			{ title: 'Music/Singers', points: 8 },
			{ title: 'Dancing Bod/Booty', points: 4 },
			{ title: 'Dice', points: 4 },
		],
	},
	{
		question: 'Name a question that mothers love to ask their grown sons.',
		answers: [
			{ title: 'Met Ms./Mr. Right?', points: 36 },
			{ title: 'Having kids?', points: 20 },
			{ title: 'Eating enough?', points: 15 },
			{ title: 'Love/miss me?', points: 9 },
			{ title: 'How are you?', points: 6 },
			{ title: 'Are you making money?', points: 4 },
		],
	},
	{
		question: 'Name something you shouldn’t be holding while you’re driving.',
		answers: [
			{ title: 'Phone', points: 59 },
			{ title: 'Food or drink', points: 13 },
			{ title: 'Alcoholic beverage', points: 12 },
			{ title: 'Crying baby', points: 11 },
			{ title: 'Murder Weapon', points: 2 },
		],
	},
	{
		question: 'Name a place that always has a long bathroom line.',
		answers: [
			{ title: 'Sports venue', points: 28 },
			{ title: 'Concert ', points: 27 },
			{ title: 'Bar/club', points: 15 },
			{ title: 'Movie', points: 8 },
			{ title: 'Theme park/fair', points: 6 },
			{ title: 'Restaurant', points: 5 },
			{ title: 'Every ladies room', points: 4 },
		],
	},
	{
		question: 'What is a common item people forget to take with them when leaving the house?',
		answers: [
			{ title: 'Keys', points: 50 },
			{ title: 'Phone ', points: 25 },
			{ title: 'Wallet/Purse', points: 15 },
			{ title: 'Sunglasses', points: 10 },
		],
	},
	{
		question: 'Name an occupation that begins with the letter "J."',
		answers: [
			{ title: 'Janitor', points: 56 },
			{ title: 'Judge/Justice', points: 19 },
			{ title: 'Jeweler', points: 8 },
			{ title: 'Jockey', points: 7 },
			{ title: 'Journalist', points: 4 },
			{ title: 'Juggler', points: 3 },
		],
	},
	{
		question: 'Name something that might be brewing.',
		answers: [
			{ title: 'Coffee', points: 37 },
			{ title: 'Beer', points: 28 },
			{ title: 'Tea', points: 17 },
			{ title: 'Trouble', points: 8 },
			{ title: 'A Storm', points: 5 },
			{ title: 'A Plot', points: 3 },
		],
	},
	{
		question: 'Name something associated with vampires.',
		answers: [
			{ title: 'Twilight', points: 33 },
			{ title: 'Blood/Sucking', points: 29 },
			{ title: 'Garlic', points: 9 },
			{ title: 'Bat', points: 7 },
			{ title: 'Cape', points: 7 },
			{ title: 'Dracula', points: 5 },
			{ title: 'Fangs', points: 4 },
		],
	},
	{
		question: 'Name something you would ask the Wizard for in the Land of Oz.',
		answers: [
			{ title: 'Money', points: 34 },
			{ title: 'Health/A New Heart', points: 17 },
			{ title: 'A Brain', points: 8 },
			{ title: 'Hot Bod', points: 7 },
			{ title: 'Peace on Earth', points: 6 },
			{ title: 'Love', points: 5 },
			{ title: 'Happiness', points: 4 },
		],
	},
];
